# DA Process here...

In [1]:
import pandas as pd
import numpy as np

In [2]:

ipl_matches = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQG9rp1Zzv4WcMBI1M9tAE_qJWKz2MCfH8UPTni2WMTjJqC7ew1gHnDjoBPHsuV9eF-9ECOZRR3lPFA/pub?gid=1361615103&single=true&output=csv"
matches = pd.read_csv(ipl_matches)

In [3]:
matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [4]:
list(set(list(matches['Team1'])+list(matches['Team2'])))

['Kings XI Punjab',
 'Rising Pune Supergiant',
 'Delhi Capitals',
 'Kochi Tuskers Kerala',
 'Mumbai Indians',
 'Gujarat Titans',
 'Chennai Super Kings',
 'Punjab Kings',
 'Rajasthan Royals',
 'Kolkata Knight Riders',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Rising Pune Supergiants',
 'Lucknow Super Giants',
 'Pune Warriors',
 'Sunrisers Hyderabad',
 'Royal Challengers Bangalore',
 'Deccan Chargers']

In [5]:
matches.head(2)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [6]:
team1 = 'Rajasthan Royals'
team2 = 'Royal Challengers Bangalore'

In [7]:
tempdf=matches[(matches['Team1']==team1) & (matches['Team2']==team2) | (matches['Team1']==team2) &(matches['Team2']==team1)]

In [8]:
total_matches=tempdf.shape[0]

In [9]:
matcheswon_team1=tempdf['WinningTeam'].value_counts()[team1]
matcheswon_team2=tempdf['WinningTeam'].value_counts()[team2]
draw = total_matches-(matcheswon_team1+matcheswon_team2)

In [10]:
def team_vs_team(team1,team2):
    tempdf=matches[(matches['Team1']==team1) & (matches['Team2']==team2) | (matches['Team1']==team2) &(matches['Team2']==team1)]
    total_matches=tempdf.shape[0]
    matcheswon_team1=tempdf['WinningTeam'].value_counts()[team1]
    matcheswon_team2=tempdf['WinningTeam'].value_counts()[team2]
    draws = total_matches-(matcheswon_team1+matcheswon_team2)

    response = {
        'total_matches':total_matches,
        team1:matcheswon_team1,
        team2:matcheswon_team2,
        'draw':draws
    }

    return response

In [11]:
team_vs_team('Chennai Super Kings','Royal Challengers Bangalore')

{'total_matches': 29,
 'Chennai Super Kings': 19,
 'Royal Challengers Bangalore': 10,
 'draw': 0}

In [12]:
team = 'Chennai Super Kings'
df= matches[(matches['Team1'] == team) | (matches['Team2'] == team)].copy()
matches_played= df.shape[0]
matches_won = df['WinningTeam']==team
matches_won =matches_won.sum()
nr = df[df.WinningTeam.isnull()].shape[0]
loss = matches_played - (matches_won+nr)
title = df[(df.MatchNumber=='Final')& (df.WinningTeam==team)].shape[0]
title

4

In [13]:
ball_by_ball = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQRLWYXE_vdPnPKe7LplgYx5qLt0rb1T1oh0zZqbaapMfYrCqbnl8Nd2OnlHnO_46VJUNvwQv4E8fwe/pub?gid=1894391710&single=true&output=csv')

In [14]:
ball_by_ball.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [15]:
# batter = 'JC Buttler'
balldf = ball_by_ball.copy()
batsman= balldf [(balldf ['batter'] == batter)]
batsman_total_runs = batsman['batsman_run'].sum()
batsman_total_ball_faced = batsman[~(batsman['extra_type'] == 'wides')].shape[0]
batsman_total_ball_faced
batsman_strike_rate = batsman_total_runs/batsman_total_ball_faced*100
fours = batsman[batsman['batsman_run']==4].shape[0]
six = batsman[batsman['batsman_run']==6].shape[0]
innings = batsman['ID'].unique().shape[0]
gb = batsman.groupby('ID').sum()
fifties =gb[(gb['batsman_run']>=50) & (gb['batsman_run']<100)].shape[0]
hundred = gb[gb['batsman_run']>=100].shape[0]
highestscore =gb['batsman_run'].sort_values(ascending=False).head(1).values[0]
outs = batsman[batsman['player_out']==batter].shape[0]
average = batsman_total_runs/outs

NameError: name 'batter' is not defined

In [ ]:
fours
six
innings
average

In [ ]:
winningteamseasom=matches[matches["MatchNumber"]=="Final"][['Season','WinningTeam']]
SeasonWinner= winningteamseasom.set_index('Season')

In [ ]:
SeasonWinner.to_dict()

In [16]:
# superover=matches[matches['SuperOver'] == 'Y'][['Date','Team1','Team2','WinningTeam']]
# yo = []
# # for i in superover['Date']:
# #     print(i)
    
# # for Team1 in superover['Team1']:
# #     print(Team1)

# # for Team2 in superover['Team2']:
# #     print(Team2)

# for Winner in superover['WinningTeam']:
#     # print(Winner)

In [ ]:
team = 'Mumbai Indians'
tosswinmatchwin=matches[matches['TossWinner'] == matches['WinningTeam']]
# matches[matches["MatchNumber"]=="Final"]
# tosswinmatchwin[(tosswinmatchwin['Team1'] == team == tosswinmatchwin['WinningTeam'] ) | (tosswinmatchwin['Team1'] ==team == tosswinmatchwin['WinningTeam'] ) ]

In [ ]:
venues=matches[['City','Venue']]
venues=venues.drop_duplicates()
venues=venues.set_index('City')
venues= venues.to_dict()
# type(venues)

# venues.astype('string')
venues
# venues.info()

In [ ]:
venues=matches[['City','Venue']]
venues=venues.drop_duplicates()
venues=venues.set_index('City')
venues

In [ ]:
venue = 'Chennai'
team = 'Chennai Super Kings'
played2=matches[(matches['City'] ==venue) & (matches['Team1'] == team)]
t1=played2.shape[0]

played1=matches[(matches['City'] ==venue) & (matches['Team2'] == team)]
t2=played1.shape[0]
venuematch_played = t1+t2
# venuematch_played
won=played2[played2.append(played1)['WinningTeam']==team].shape[0]
loss = venuematch_played-won
winpercentage = won/venuematch_played*100
winpercentage

In [ ]:
matches[~matches['MatchNumber'].str.isdigit()]['Player_of_Match'].value_counts()

In [23]:
batsmandata = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRwgITbG6BjnxnNvxkj8YKJem6EIJjaejYK4KHMRbI5eHaYDVDP5RSv5OLd0rN1wWRrTE4EqYuUqb3a/pub?gid=655438454&single=true&output=csv'
batsman_run = pd.read_csv(batsmandata)

In [24]:
batsman_run.head()

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

In [25]:
# batsman['batsman_run'].ascending(False)
batsman_run.rank()
batsman_run['batting_rank']=batsman_run['batsman_run'].rank(ascending=False)
# batsman_run.sort_values('batting_rank')
runbatsman=batsman_run.sort_values('batting_rank')

In [ ]:
runbatsman=runbatsman[['batter','batsman_run']].set_index('batter').to_dict()
runbatsman

In [17]:
# six = matches[matches['batsman_runs'] == 6]
# matches
ipl = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQRLWYXE_vdPnPKe7LplgYx5qLt0rb1T1oh0zZqbaapMfYrCqbnl8Nd2OnlHnO_46VJUNvwQv4E8fwe/pub?gid=1894391710&single=true&output=csv')

six = ipl[ipl['batsman_run'] == 6]

# six.groupby('batsman')['batsman'].value_counts().sort_values(ascending=False)
# six.groupby('batsman')['batsman'].count().sort_values(ascending=False)
six

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
16,1312200,1,2,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,6,0,6,0,0,NaN,NaN,NaN,Rajasthan Royals
22,1312200,1,3,5,YBK Jaiswal,Yash Dayal,JC Buttler,NaN,6,0,6,0,0,NaN,NaN,NaN,Rajasthan Royals
103,1312200,1,17,2,TA Boult,R Sai Kishore,R Parag,NaN,6,0,6,0,0,NaN,NaN,NaN,Rajasthan Royals
107,1312200,1,17,6,OC McCoy,R Sai Kishore,R Parag,NaN,6,0,6,0,0,NaN,NaN,NaN,Rajasthan Royals
142,1312200,2,3,5,MS Wade,M Prasidh Krishna,Shubman Gill,NaN,6,0,6,0,0,NaN,NaN,NaN,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225848,335982,1,19,2,BB McCullum,P Kumar,Mohammad Hafeez,NaN,6,0,6,0,0,NaN,NaN,NaN,Kolkata Knight Riders
225852,335982,1,19,6,BB McCullum,P Kumar,Mohammad Hafeez,NaN,6,0,6,0,0,NaN,NaN,NaN,Kolkata Knight Riders
225882,335982,2,4,4,JH Kallis,AB Agarkar,W Jaffer,NaN,6,0,6,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225932,335982,2,12,1,P Kumar,LR Shukla,Z Khan,NaN,6,0,6,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225944,335982,2,13,6,P Kumar,SC Ganguly,SB Joshi,NaN,6,0,6,0,0,NaN,NaN,NaN,Royal Challengers Bangalore

In [18]:
noofsixes = six.groupby('batter')['batter'].count().sort_values(ascending=False).to_dict()
noofsixes

{'CH Gayle': 359,
 'AB de Villiers': 253,
 'RG Sharma': 241,
 'MS Dhoni': 229,
 'KA Pollard': 224,
 'V Kohli': 219,
 'DA Warner': 216,
 'SK Raina': 204,
 'SR Watson': 190,
 'RV Uthappa': 182,
 'AD Russell': 175,
 'AT Rayudu': 164,
 'KL Rahul': 164,
 'YK Pathan': 161,
 'SV Samson': 158,
 'Yuvraj Singh': 149,
 'S Dhawan': 137,
 'JC Buttler': 135,
 'KD Karthik': 134,
 'BB McCullum': 130,
 'RR Pant': 129,
 'GJ Maxwell': 127,
 'DR Smith': 117,
 'DA Miller': 113,
 'HH Pandya': 111,
 'N Rana': 111,
 'F du Plessis': 109,
 'MK Pandey': 106,
 'V Sehwag': 106,
 'Q de Kock': 106,
 'SS Iyer': 99,
 'AC Gilchrist': 92,
 'MA Agarwal': 91,
 'M Vijay': 91,
 'RA Jadeja': 90,
 'Ishan Kishan': 85,
 'SA Yadav': 84,
 'AM Rahane': 80,
 'JP Duminy': 79,
 'NV Ojha': 79,
 'AJ Finch': 78,
 'SE Marsh': 78,
 'WP Saha': 76,
 'RA Tripathi': 68,
 'CA Lynn': 66,
 'DJ Bravo': 66,
 'N Pooran': 65,
 'KS Williamson': 64,
 'EJG Morgan': 64,
 'SP Narine': 63,
 'DJ Hussey': 60,
 'SPD Smith': 60,
 'G Gambhir': 59,
 'DJ Hooda': 56,
 'JA Morkel': 55,
 'PP Shaw': 55,
 'JM Bairstow': 55,
 'AR Patel': 54,
 'MM Ali': 53,
 'MEK Hussey': 52,
 'SO Hetmyer': 52,
 'SS Tiwary': 50,
 'KH Pandya': 50,
 'PA Patel': 49,
 'MP Stoinis': 48,
 'Shubman Gill': 47,
 'LRPL Taylor': 46,
 'ML Hayden': 44,
 'JH Kallis': 44,
 'LMP Simmons': 44,
 'BJ Hodge': 43,
 'RD Gaikwad': 43,
 'M Vohra': 43,
 'SC Ganguly': 42,
 'Harbhajan Singh': 42,
 'A Symonds': 41,
 'DPMD Jayawardene': 40,
 'LS Livingstone': 40,
 'KM Jadhav': 40,
 'MK Tiwary': 40,
 'KP Pietersen': 40,
 'ST Jayasuriya': 39,
 'KK Nair': 39,
 'CL White': 38,
 'IK Pathan': 38,
 'S Dube': 38,
 'Mandeep Singh': 37,
 'Y Venugopal Rao': 37,
 'E Lewis': 36,
 'D Padikkal': 36,
 'CH Morris': 35,
 'R Tewatia': 35,
 'STR Binny': 35,
 'BA Stokes': 32,
 'HH Gibbs': 31,
 'CJ Anderson': 31,
 'SR Tendulkar': 29,
 'AD Mathews': 29,
 'R Dravid': 28,
 'S Badrinath': 28,
 'MC Henriques': 28,
 'V Shankar': 28,
 'MR Marsh': 28,
 'KC Sangakkara': 27,
 'NLTC Perera': 26,
 'PJ Cummins': 26,
 'TL Suman': 26,
 'Abhishek Sharma': 25,
 'TM Dilshan': 24,
 'AK Markram': 23,
 'OA Shah': 23,
 'MS Bisla': 23,
 'JP Faulkner': 23,
 'R Powell': 22,
 'YBK Jaiswal': 22,
 'Rashid Khan': 22,
 'R Parag': 22,
 'RM Patidar': 21,
 'VR Iyer': 21,
 'R Ashwin': 21,
 'Shakib Al Hasan': 21,
 'HM Amla': 21,
 'PC Valthaty': 20,
 'AM Nayar': 20,
 'SW Billings': 20,
 'JD Ryder': 19,
 'M Shahrukh Khan': 19,
 'DT Christian': 19,
 'BCJ Cutting': 19,
 'GJ Bailey': 19,
 'C de Grandhomme': 18,
 'PP Chawla': 18,
 'AL Menaria': 18,
 'DJG Sammy': 18,
 'SM Curran': 18,
 'S Sohal': 18,
 'JO Holder': 17,
 'P Kumar': 17,
 'CR Brathwaite': 16,
 'P Negi': 16,
 'RS Bopara': 16,
 'DB Das': 16,
 'TH David': 16,
 'Tilak Varma': 16,
 'LR Shukla': 16,
 'RN ten Doeschate': 15,
 'MJ Guptill': 15,
 'A Ashish Reddy': 15,
 'KV Sharma': 14,
 'Abdul Samad': 14,
 'JC Archer': 14,
 'MV Boucher': 13,
 'PBB Rajapaksa': 13,
 'MK Lomror': 13,
 'LA Pomersbach': 13,
 'HV Patel': 13,
 'SN Khan': 13,
 'PD Collingwood': 13,
 'Azhar Mahmood': 13,
 'R Bhatia': 13,
 'JM Sharma': 12,
 'DP Conway': 12,
 'K Gowtham': 12,
 'Shahbaz Ahmed': 11,
 'D Brevis': 11,
 'JR Hopes': 11,
 'Gurkeerat Singh': 11,
 'AP Tare': 11,
 'M Manhas': 10,
 'Mohammad Nabi': 10,
 'SA Asnodkar': 10,
 'Bipul Sharma': 9,
 'RK Singh': 9,
 'R Vinay Kumar': 9,
 'UBT Chand': 9,
 'MF Maharoof': 9,
 'GC Smith': 9,
 'JJ Roy': 9,
 'PK Garg': 9,
 'JEC Franklin': 9,
 'Washington Sundar': 9,
 'Y Nagar': 9,
 'K Goel': 9,
 'DB Ravi Teja': 9,
 'KS Bharat': 8,
 'SM Katich': 8,
 'MD Mishra': 8,
 'B Lee': 8,
 'UT Yadav': 8,
 'SN Thakur': 8,
 'SM Pollock': 8,
 'SE Rutherford': 8,
 'MS Gony': 8,
 'TM Head': 8,
 'RE van der Merwe': 8,
 'C Munro': 8,
 'KK Cooper': 8,
 'Kamran Akmal': 8,
 'Anuj Rawat': 7,
 'A Badoni': 7,
 'MN Samuels': 7,
 'AS Raut': 7,
 'Lalit Yadav': 7,
 'B Chipli': 7,
 'S Anirudha': 7,
 'MJ McClenaghan': 7,
 'MG Johnson': 7,
 'Misbah-ul-Haq': 6,
 'DL Chahar': 6,
 'Shahid Afridi': 6,
 'AD Hales': 6,
 'R Sathish': 6,
 'R Dhawan': 6,
 'CM Gautam': 6,
 'MJ Lumb': 6,
 'SK Warne': 6,
 'M Kaif': 6,
 'JD Unadkat': 6,
 'K Rabada': 6,
 'A Mishra': 5,
 'SL Malinga': 5,
 'JDP Oram': 5,
 'CA Ingram': 5,
 'Harpreet Brar': 5,
 'P Dogra': 5,
 'OF Smith': 5,
 'J Botha': 5,
 'DJ Harris': 5,
 'R Shepherd': 5,
 'BJ Rohrer': 5,
 'AJ Tye': 5,
 'VVS Laxman': 5,
 'AA Jhunjhunwala': 5,
 'Sachin Baby': 5,
 'Umar Gul': 5,
 'B Akhil': 5,
 'DJM Short': 5,
 'M Morkel': 5,
 'AB Agarkar': 5,
 'Shashank Singh': 4,
 'TG Southee': 4,
 'AB McDonald': 4,
 'CA Pujara': 4,
 'MM Sharma': 4,
 'D Wiese': 4,
 'Ankit Sharma': 4,
 'NM Coulter-Nile': 4,
 'RE Levi': 4,
 'DJ Jacobs': 4,
 'RD Chahar': 4,
 'RJ Harris': 3,
 'SP Fleming': 3,
 'CJ Jordan': 3,
 'B Kumar': 3,
 'PVD Chameera': 3,
 'B Sai Sudharsan': 3,
 'SB Styris': 3,
 'S Vidyut': 3,
 'RR Rossouw': 3,
 'SB Bangar': 3,
 'R Sharma': 3,
 'RJ Quiney': 3,
 'Avesh Khan': 3,
 'AC Voges': 3,
 'SP Goswami': 3,
 'W Jaffer': 3,
 'J Suchith': 3,
 'DR Sams': 3,
 'UT Khawaja': 3,
 'LJ Wright': 3,
 'DW Steyn': 3,
 'TK Curran': 3,
 'WPUJC Vaas': 3,
 'MJ Santner': 3,
 'KA Jamieson': 3,
 'YV Takawale': 3,
 'A Manohar': 3,
 'D Pretorius': 3,
 'JDS Neesham': 2,
 'Joginder Sharma': 2,
 'Salman Butt': 2,
 'ER Dwivedi': 2,
 'A Flintoff': 2,
 'RT Ponting': 2,
 'AD Nath': 2,
 'VR Aaron': 2,
 'I Sharma': 2,
 'LH Ferguson': 2,
 'S Gopal': 2,
 'KC Cariappa': 2,
 'SA Abbott': 2,
 'SS Prabhudessai': 2,
 'Kuldeep Yadav': 2,
 'SD Chitnis': 2,
 'AP Majumdar': 2,
 'AUK Pathan': 2,
 'PR Shah': 2,
 'GD Phillips': 2,
 'DS Kulkarni': 2,
 'BB Samantray': 2,
 'CR Woakes': 2,
 'PA Reddy': 2,
 'R Bishnoi': 2,
 'P Simran Singh': 2,
 'TA Boult': 2,
 'R Rampaul': 2,
 'DH Yagnik': 2,
 'AS Yadav': 2,
 'AC Blizzard': 2,
 'TR Birt': 2,
 'Shivam Mavi': 2,
 'Mohammed Siraj': 2,
 'Z Khan': 2,
 'Mohammed Shami': 2,
 'DJ Thornely': 2,
 'DL Vettori': 2,
 'MS Wade': 2,
 'Mohammad Hafeez': 2,
 'A Nehra': 1,
 'T Kohli': 1,
 'A Choudhary': 1,
 'Sunny Singh': 1,
 'TS Mills': 1,
 'AP Dole': 1,
 'T Banton': 1,
 'AD Mascarenhas': 1,
 'T Henderson': 1,
 'Sohail Tanvir': 1,
 'AS Rajpoot': 1,
 'TU Deshpande': 1,
 'SW Tait': 1,
 'AN Ahmed': 1,
 'A Mithun': 1,
 'AB Barath': 1,
 'AF Milne': 1,
 'WD Parnell': 1,
 'AC Thomas': 1,
 'VH Zol': 1,
 'Vishnu Vinod': 1,
 'JJ van der Wath': 1,
 'SP Jackson': 1,
 'AT Carey': 1,
 'Mohsin Khan': 1,
 'MN van Wyk': 1,
 'DR Shorey': 1,
 'FY Fazal': 1,
 'MC Juneja': 1,
 'MA Khote': 1,
 'GH Vihari': 1,
 'M Theekshana': 1,
 'M Rawat': 1,
 'M Kartik': 1,
 'M Jansen': 1,
 'M Ashwin': 1,
 'H Klaasen': 1,
 'LPC Silva': 1,
 'L Ronchi': 1,
 'L Balaji': 1,
 'KW Richardson': 1,
 'I Udana': 1,
 'Iqbal Abdulla': 1,
 'KMA Paul': 1,
 'J Yadav': 1,
 'KJ Abbott': 1,
 'KB Arun Karthik': 1,
 'K Upadhyay': 1,
 'JR Philippe': 1,
 'JPR Scantlebury-Searles': 1,
 'JJ Bumrah': 1,
 'Mustafizur Rahman': 1,
 'N Jagadeesan': 1,
 'DJ Malan': 1,
 'RR Powar': 1,
 'SK Trivedi': 1,
 'Anirudh Singh': 1,
 'SD Lad': 1,
 'Ankit Soni': 1,
 'Anmolpreet Singh': 1,
 'S Rana': 1,
 'Anureet Singh': 1,
 'Ramandeep Singh': 1,
 'RV Patel': 1,
 'RV Gomez': 1,
 'RR Sarwan': 1,
 'RR Raje': 1,
 'RP Singh': 1,
 'NK Patel': 1,
 'RJ Peterson': 1,
 'BA Bhatt': 1,
 'BJ Haddin': 1,
 'Basil Thampi': 1,
 'JM Kemp': 1,
 'PWH de Silva': 1,
 'CK Langeveldt': 1,
 'P Sahu': 1,
 'OC McCoy': 1,
 'DE Bollinger': 1,
 'NT Ellis': 1,
 'NL McCullum': 1,
 'R McLaren': 1}

In [19]:
from16over = ipl[ipl['overs'] >15]
from16over=from16over[( from16over['batsman_run']==4 ) | (from16over['batsman_run']==6)]

from16over.groupby('batter')['batter'].count().sort_values(ascending=False)

batter
MS Dhoni          347
KA Pollard        237
AB de Villiers    218
KD Karthik        190
RG Sharma         168
                 ...
Anirudh Singh       1
Ankit Soni          1
Anuj Rawat          1
PJ Sangwan          1
NL McCullum         1
Name: batter, Length: 411, dtype: int64

In [28]:
# filtered_VK = ipl[ipl['batter'] == 'V Kohli']
# filtered_VK.groupby('bowling_team')['batsman_runs'].sum().reset_index()
deliveries = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQEJnmI-E6FluLo5khJ8JNuO9gYS0d3gZ0F1mY7zNca3ozajy26OTKAsoHjvyVdyI1CJHKGdrVidtrI/pub?gid=586204712&single=true&output=csv')
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [20]:
filtered_batsman = deliveries[deliveries['batsman'] == 'V Kohli']
filtered_batsman.groupby('bowling_team')['batsman_runs'].sum().to_dict()

NameError: name 'deliveries' is not defined

In [ ]:
# deliveries

In [30]:
# matches
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [31]:
matches

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [38]:
matches2= pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQ0V9jpOUKMEtofos-emhGRv0hLvvERxDkCkpfHdey_9_wcRmRgJ8FsH55LLTzCpeOqb6NO3ZdkrdYe/pub?gid=1665367792&single=true&output=csv')

In [40]:

ipl_tempdf = deliveries.merge(matches2,left_on='match_id',right_on='id')
ipl_tempdf
ipl_tempdf.groupby(['season','batsman'])['batsman_runs'].sum().reset_index().sort_values('batsman_runs',ascending=False).drop_duplicates(['season'],keep='first').sort_index()

      season       batsman  batsman_runs
115     2008      SE Marsh           616
229     2009     ML Hayden           572
446     2010  SR Tendulkar           618
502     2011      CH Gayle           608
684     2012      CH Gayle           733
910     2013    MEK Hussey           733
1088    2014    RV Uthappa           660
1148    2015     DA Warner           562
1383    2016       V Kohli           973
1422    2017     DA Warner           641

In [34]:
matches.head(1)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon